# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidbit', '0004_auto_20160607_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmldata',
            name='linktoparent',
            field=models.CharField(max_length=5024, null=True),
        ),
        migrations.AddField(
            model_name='xmldata',
            name='nodeparentCode',
            field=models.IntegerField(default=0),
        ),
    ]
