# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidbit', '0006_auto_20160610_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmldata',
            name='nodedata',
            field=models.CharField(max_length=10024, null=True),
        ),
    ]
